name: Build & Test

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Liberate disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Checkout Lean Same Branch
        id: lean-same-branch
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: ${{ github.ref }}
          repository: QuantConnect/Lean
          path: Lean

      - name: Checkout Lean Master
        if: steps.lean-same-branch.outcome != 'success'
        uses: actions/checkout@v2
        with:
          repository: QuantConnect/Lean
          path: Lean

      - name: Move Lean
        run: mv Lean ../Lean

      - uses: addnab/docker-run-action@v3
        with:
          image: quantconnect/lean:foundation
          options: --workdir /__w/Lean.Brokerages.NordPoolIntraday/Lean.Brokerages.NordPoolIntraday -v /home/runner/work:/__w -e QC_NordPoolIntraday_BROKERAGE_KEY=${{ secrets.QC_NordPoolIntraday_BROKERAGE_KEY }} -e QC_NordPoolIntraday_BROKERAGE_SECRET=${{ secrets.QC_NordPoolIntraday_BROKERAGE_SECRET }} -e QC_JOB_USER_ID=${{ secrets.QC_JOB_USER_ID }} -e QC_API_ACCESS_TOKEN=${{ secrets.QC_API_ACCESS_TOKEN }} -e QC_JOB_ORGANIZATION_ID=${{ secrets.QC_JOB_ORGANIZATION_ID }}
          shell: bash
          run: |
            # Build
            dotnet build /p:Configuration=Release /v:quiet /p:WarningLevel=1 QuantConnect.NordPoolIntradayBrokerage.sln && \
            # Run Tests
            dotnet test ./QuantConnect.NordPoolIntradayBrokerage.Tests/bin/Release/QuantConnect.Brokerages.NordPoolIntraday.Tests.dll
